### ISSUE TITLE
clickable backdrop when data-backdrop="static"

### ISSUE THREAD

**Issue by etuctida** [radogado/bootstrap-modal-ios#1]
Great plugin, btw.
But when I set data-backdrop="static" to prevent backdrop click to close is not working. user still can close modal by clicking backdrop.

**Comment by radogado** [comment]
Thank you. I'm not aware of **data-backdrop**, can you please provide an example page? Thanks!

**Comment by etuctida** [comment]
my bad, idk why it works. i'll close this issue.
